import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from 'file:///C:/Users/Suxrob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs';
import {resolvePresentationFont,finalizePresentation} from 'file:///C:/Users/Suxrob/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='D:/G59/Model_6/Dori_Qidiruv_bot', build=root+'/reports/presentation-build', out=root+'/reports/presentation/Dori_Qidiruv_hamkorlik.pptx';
const skill='C:/Users/Suxrob/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const font=resolvePresentationFont();
console.log('Font',font);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const ink='#123E46',teal='#087E86', muted='#50666B',paper='#F4F8F7';
function text(s,t,x,y,w,h,size=28,color=ink,bold=false){const o=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});o.text=t;o.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return o;}
function slide(title,dark=false){const s=p.slides.add();s.background.fill=dark?ink:paper;if(title)text(s,title,76,58,1128,116,46,dark?'#FFFFFF':ink,true);text(s,String(p.slides.items.length).padStart(2,'0'),1150,661,60,26,18,dark?'#9BC8C9':muted);return s;}
async function icon(s,name,x,y,size){s.images.add({blob:new Uint8Array(await fs.readFile(root+'/src/main/resources/static/icons/'+name+'.png')),contentType:'image/png',alt:name,fit:'contain',position:{left:x,top:y,width:size,height:size}});}
function note(s,t){s.speakerNotes.textFrame.setText(t);}
let s=slide('',true);text(s,'Dori Qidiruv',76,169,820,100,76,'#FFFFFF',true);text(s,'Dorixonalar uchun\nhamkorlik taklifi',80,292,780,160,43,'#C3ECE5');text(s,'Mijoz kerakli dorini topsin.\nDorixonangiz bilan bog‘lansin.',80,509,810,90,29,'#FFFFFF');await icon(s,'pharmacy',905,195,270);note(s,'Dorixona rahbari uchun kirish: Dori Qidiruv mijozlarga dori mavjud bo‘lgan dorixonani topish va oldindan band qilish imkonini taqdim etadi. Manba: src/main/resources/static/taqdimot.html va index.html.');
s=slide('Dori izlayotgan mijozga ko‘rinish');text(s,'Mijozning ehtiyoji',78,224,480,52,32,teal,true);text(s,'Kerakli dori qayerda borligini, narxini va dorixonaga qanday borishni bilish.',78,296,485,180,32);text(s,'Dorixona uchun imkoniyat',688,224,510,52,32,teal,true);text(s,'Mavjud mahsulotlarni ularni qidirayotgan odamlarga ko‘rsatish va murojaatni qabul qilish.',688,296,500,200,32);text(s,'Maqsad: dori qidiruvini dorixona bilan bog‘lanishga aylantirish.',78,575,1110,60,28,muted);note(s,'Bu slayd mijoz ehtiyoji va xizmat taklifini tushuntiradi. Savdo o‘sishi yoki auditoriya hajmi bo‘yicha kafolat berilmaydi.');
s=slide('Xaridor uchun qidiruv va bron');await icon(s,'search',940,250,235);const features=[['Dori nomi bo‘yicha qidiruv','O‘zbekcha va ruscha nomlar bilan izlash.'],['Dorixonani tanlash','Narx, manzil va joylashuvga qarab masofani ko‘rish.'],['Oldindan band qilish','Miqdorni tanlash va bron so‘rovini yuborish.']];features.forEach((a,i)=>{text(s,a[0],78,205+i*139,800,45,31,teal,true);text(s,a[1],78,258+i*139,800,65,26);});note(s,'Manbalar: src/main/resources/static/index.html qidiruv, geolokatsiya, narx va bron funksiyalari. src/main/java/com/example/dori_qidiruv_bot/controller/BronController.java. Masofa foydalanuvchi joylashuvi mavjud bo‘lganda ko‘rinadi.');
s=slide('Qidiruvdan mahsulotni olib ketishgacha');const steps=[['01','Qidirish','Mijoz dori nomini yozadi va dorixonani tanlaydi.'],['02','Bron','Kerakli miqdor bilan band qilish so‘rovini yuboradi.'],['03','Tasdiqlash','Dorixona mahsulotni tayyorlaydi va javob beradi.'],['04','Olib ketish','Mijoz kod bilan keladi, dorixona topshirishni qayd etadi.']];steps.forEach((a,i)=>{const y=192+i*111;text(s,a[0],80,y,84,65,43,teal,true);text(s,a[1],193,y,260,50,30,ink,true);text(s,a[2],466,y,716,82,27);});note(s,'Manba: src/main/resources/static/taqdimot.html, Qanday ishlaydi bo‘limi. Dorixona bilan bron jarayonini amaliy namoyishda birgalikda tekshirish taklif etiladi.');
s=slide('Dorixona uchun ish kabineti');text(s,'Mahsulot va qoldiq',78,222,740,50,34,teal,true);text(s,'Mahsulot qo‘shish, narxni kiritish,\nkirim va chiqimni yuritish.',78,285,775,105,30);text(s,'Bronlar va kundalik ish',78,425,745,50,34,teal,true);text(s,'Kelgan buyurtmaga javob berish,\ntopshirishni belgilash va hisobotni ko‘rish.',78,488,800,105,30);await icon(s,'box',960,276,225);note(s,'Manba: src/main/resources/static/taqdimot.html, dorixona ish kabineti tavsifi. Qo‘shimcha manba: service/OmborService.java va service/BronService.java.');
s=slide('Hamkorlikdagi vazifalar');text(s,'Dori Qidiruv jamoasi',78,215,530,55,34,teal,true);text(s,'Dorixonani ulashga yordam beradi.\n\nKabinet va bron jarayonini tushuntiradi.\n\nTexnik murojaatlarni qabul qiladi.',78,294,510,280,28);text(s,'Dorixona jamoasi',689,215,510,55,34,teal,true);text(s,'Vakil va dorixona ma’lumotlarini beradi.\n\nNarx va qoldiqni yangilab boradi.\n\nBronlarga javob beradigan xodimni belgilaydi.',689,294,505,300,28);note(s,'Hamkorlik uchun taklif etilayotgan vazifalar taqsimoti. Yakuniy xizmat doirasi va tomonlar majburiyatlari kelishuvda belgilanadi.');
s=slide('Ulanish va sinov jarayoni');const onboard=[['Tanishuv','Bot imkoniyatlarini birga ko‘rib chiqamiz.'],['Ro‘yxatdan o‘tish','Dorixona va mas’ul vakil ma’lumotlarini tekshiramiz.'],['Mahsulotlarni kiritish','Narx va qoldiqni tayyorlab, sinov bronini o‘tkazamiz.'],['Natijani baholash','Murojaatlar va ish qulayligini muhokama qilamiz.']];onboard.forEach((a,i)=>{text(s,String(i+1),79,194+i*110,72,60,43,teal,true);text(s,a[0],183,194+i*110,350,50,30,ink,true);text(s,a[1],576,194+i*110,612,84,27);});note(s,'Taklif etilayotgan ish tartibi. Sinovning muddati va to‘lov shartlari oldindan kelishiladi. Dorixona vakilini tekshirish jarayoni loyiha taqdimotida tasvirlangan.');
s=slide('Obuna va hamkorlik shartlari');text(s,'Dorixona obunasi',78,209,1010,60,39,teal,true);text(s,'Xaridor uchun qidiruv bepul.\nDorixona uchun xizmat obuna asosida taklif etiladi.',78,299,1080,116,33);text(s,'Narx va muddat',78,462,460,50,30,ink,true);text(s,'Tarif, sinov davri va xizmat ko‘rsatish shartlarini hamkorlikdan oldin kelishamiz.',78,523,1055,92,29);note(s,'Manba: src/main/resources/static/taqdimot.html, Biznes modeli bo‘limi. Unda narxlar hali belgilanmagani qayd etilgan. Shu sababli ushbu taqdimot aniq tarif, chegirma yoki bepul sinov va’dasini bermaydi.');
s=slide('Hamkorlikni boshlash',true);text(s,'Dorixonangiz uchun\namaliy namoyish',78,220,875,160,58,'#FFFFFF',true);text(s,'Birgalikda bitta mahsulotni kiritib,\nqidiruv va bron jarayonini ko‘rib chiqamiz.',80,411,1010,98,32,'#C3ECE5');text(s,'Xaridor boti: @dori_UzBot\nDorixonalar uchun: @Anvarovich_02_bot',80,552,1070,88,27,'#FFFFFF');note(s,'Manba: src/main/resources/static/taqdimot.html footer. Bot foydalanuvchi nomlari loyiha fayllaridan olindi. Ularning jonli holati ushbu taqdimotni tayyorlashda tekshirilmadi.');
const candidate=build+'/candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:out,pythonExecutable:'C:/Users/Suxrob/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/validation.json'});
for(let i=0;i<p.slides.items.length;i++){const blob=await p.export({slide:p.slides.items[i],format:'png',scale:0.8});await fs.writeFile(build+'/slide-'+(i+1)+'.png',new Uint8Array(await blob.arrayBuffer()));}
console.log(out);

