export interface Category {
  slug: string
  uz: string
  ru: string
  descUz: string
  descRu: string
  search: string[]
  iconName: string
  color: string
  bgGradient: string
  accentColor: string
}

export const categories: Category[] = [
  {
    slug: 'bosh-ogriq',
    uz: "Bosh og'rig'i",
    ru: 'Головная боль',
    descUz: "Bosh og'rig'iga qarshi dorilar — og'riq qoldiruvchi va spazmolitiklar",
    descRu: 'Лекарства от головной боли — анальгетики и спазмолитики',
    search: ['парацетамол', 'анальгин', 'цитрамон', 'но-шпа', 'спазмалгон'],
    iconName: 'Brain',
    color: 'bg-purple-50 text-purple-500',
    bgGradient: 'from-purple-50 via-purple-50/40 to-indigo-50',
    accentColor: 'text-purple-600',
  },
  {
    slug: 'shamollash',
    uz: 'Shamollash va gripp',
    ru: 'Простуда и грипп',
    descUz: "Shamollash va grippga qarshi dorilar — issiqlik tushiruvchi, immunitet",
    descRu: 'Лекарства от простуды и гриппа — жаропонижающие, иммунитет',
    search: ['терафлю', 'колдрекс', 'фервекс', 'антигриппин', 'ринза'],
    iconName: 'Thermometer',
    color: 'bg-blue-50 text-blue-500',
    bgGradient: 'from-blue-50 via-blue-50/40 to-cyan-50',
    accentColor: 'text-blue-600',
  },
  {
    slug: 'yotal',
    uz: "Yo'tal",
    ru: 'Кашель',
    descUz: "Yo'tal va bo'g'iz og'rig'iga qarshi siroplar, tabletka va spraylar",
    descRu: 'Сиропы, таблетки и спреи от кашля и боли в горле',
    search: ['бромгексин', 'мукалтин', 'амброксол', 'лазолван', 'стрепсилс'],
    iconName: 'Wind',
    color: 'bg-teal-50 text-teal-500',
    bgGradient: 'from-teal-50 via-teal-50/40 to-emerald-50',
    accentColor: 'text-teal-600',
  },
  {
    slug: 'oshqozon',
    uz: 'Oshqozon',
    ru: 'Желудок',
    descUz: "Oshqozon va ichak kasalliklariga qarshi dorilar",
    descRu: 'Лекарства при заболеваниях желудка и кишечника',
    search: ['омепразол', 'фосфалюгель', 'мезим', 'смекта', 'маалокс'],
    iconName: 'Stethoscope',
    color: 'bg-amber-50 text-amber-500',
    bgGradient: 'from-amber-50 via-amber-50/40 to-orange-50',
    accentColor: 'text-amber-600',
  },
  {
    slug: 'yurak',
    uz: 'Yurak',
    ru: 'Сердце',
    descUz: "Yurak va qon tomir tizimiga dorilar",
    descRu: 'Препараты для сердечно-сосудистой системы',
    search: ['валидол', 'корвалол', 'нитроглицерин', 'валокордин', 'кардиомагнил'],
    iconName: 'Heart',
    color: 'bg-red-50 text-red-500',
    bgGradient: 'from-red-50 via-red-50/40 to-rose-50',
    accentColor: 'text-red-600',
  },
  {
    slug: 'qon-bosim',
    uz: 'Qon bosim',
    ru: 'Давление',
    descUz: "Qon bosimni tartibga soluvchi dorilar",
    descRu: 'Препараты для регулирования давления',
    search: ['амлодипин', 'эналаприл', 'лозартан', 'каптоприл', 'бисопролол'],
    iconName: 'Droplets',
    color: 'bg-rose-50 text-rose-500',
    bgGradient: 'from-rose-50 via-rose-50/40 to-pink-50',
    accentColor: 'text-rose-600',
  },
  {
    slug: 'allergiya',
    uz: 'Allergiya',
    ru: 'Аллергия',
    descUz: "Allergiyaga qarshi antihistamin dorilar",
    descRu: 'Антигистаминные препараты от аллергии',
    search: ['лоратадин', 'цетиризин', 'супрастин', 'зиртек', 'кларитин'],
    iconName: 'ShieldPlus',
    color: 'bg-orange-50 text-orange-500',
    bgGradient: 'from-orange-50 via-orange-50/40 to-amber-50',
    accentColor: 'text-orange-600',
  },
  {
    slug: 'antibiotiklar',
    uz: 'Antibiotiklar',
    ru: 'Антибиотики',
    descUz: "Infektsiyalarga qarshi antibiotik dorilar",
    descRu: 'Антибактериальные препараты от инфекций',
    search: ['амоксициллин', 'азитромицин', 'ципрофлоксацин', 'цефтриаксон', 'доксициклин'],
    iconName: 'Syringe',
    color: 'bg-emerald-50 text-emerald-500',
    bgGradient: 'from-emerald-50 via-emerald-50/40 to-green-50',
    accentColor: 'text-emerald-600',
  },
  {
    slug: 'bogim',
    uz: "Bo'g'im og'rig'i",
    ru: 'Боль в суставах',
    descUz: "Bo'g'im va mushak og'rig'iga qarshi dorilar",
    descRu: 'Препараты от боли в суставах и мышцах',
    search: ['диклофенак', 'ибупрофен', 'мелоксикам', 'нимесулид', 'индометацин'],
    iconName: 'Bone',
    color: 'bg-stone-100 text-stone-500',
    bgGradient: 'from-stone-50 via-stone-50/40 to-slate-50',
    accentColor: 'text-stone-600',
  },
  {
    slug: 'ogriq',
    uz: "Og'riq qoldiruvchi",
    ru: 'Обезболивающие',
    descUz: "Kuchli va oddiy og'riq qoldiruvchi dorilar",
    descRu: 'Обезболивающие препараты различной силы',
    search: ['кетанов', 'кеторол', 'нурофен', 'темпалгин', 'баралгин'],
    iconName: 'Pill',
    color: 'bg-indigo-50 text-indigo-500',
    bgGradient: 'from-indigo-50 via-indigo-50/40 to-blue-50',
    accentColor: 'text-indigo-600',
  },
  {
    slug: 'koz',
    uz: "Ko'z",
    ru: 'Глаза',
    descUz: "Ko'z uchun tomchilar va dorilar",
    descRu: 'Капли и препараты для глаз',
    search: ['визин', 'тауфон', 'офтальмоферон', 'ципромед', 'левомицетин'],
    iconName: 'Eye',
    color: 'bg-cyan-50 text-cyan-500',
    bgGradient: 'from-cyan-50 via-cyan-50/40 to-sky-50',
    accentColor: 'text-cyan-600',
  },
  {
    slug: 'diabet',
    uz: 'Diabet',
    ru: 'Диабет',
    descUz: "Diabet kasalligiga qarshi dorilar va insulin",
    descRu: 'Препараты от диабета и инсулин',
    search: ['метформин', 'глибенкламид', 'инсулин', 'диабетон', 'глюкофаж'],
    iconName: 'Sparkles',
    color: 'bg-violet-50 text-violet-500',
    bgGradient: 'from-violet-50 via-violet-50/40 to-purple-50',
    accentColor: 'text-violet-600',
  },
  {
    slug: 'bolalar',
    uz: 'Bolalar uchun',
    ru: 'Для детей',
    descUz: "Bolalar uchun xavfsiz dorilar — siroplar, tomchilar, vitaminlar",
    descRu: 'Безопасные лекарства для детей — сиропы, капли, витамины',
    search: ['нурофен', 'панадол', 'эспумизан', 'саб симплекс', 'аквамарис'],
    iconName: 'Baby',
    color: 'bg-pink-50 text-pink-500',
    bgGradient: 'from-pink-100 via-pink-50 to-yellow-50',
    accentColor: 'text-pink-500',
  },
  {
    slug: 'vitaminlar',
    uz: 'Vitaminlar',
    ru: 'Витамины',
    descUz: "Vitaminlar va mineral komplekslar — immunitet uchun",
    descRu: 'Витамины и минеральные комплексы — для иммунитета',
    search: ['витамин', 'компливит', 'мульти-табс', 'супрадин', 'алфавит'],
    iconName: 'Apple',
    color: 'bg-green-50 text-green-500',
    bgGradient: 'from-green-50 via-green-50/40 to-emerald-50',
    accentColor: 'text-green-600',
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug)
}
